feature: upgrade React to 18
tkeel-io/console pull request #600
Opened 2022-05-11 08:44 UTC by donniean

2022-05-11 09:09 UTC, donniean commented on package.json
>      "@types/axios": "^0.14.0",
test

2022-05-11 09:09 UTC, donniean commented on package.json
>      "@types/axios": "^0.14.0",
test apply

2022-05-11 09:22 UTC, jackzerone requested changes
approve

2022-05-11 09:24 UTC, jackzerone approved these changes

2022-05-12 01:05 UTC, lunz1207 commented
/ok-to-test

2022-05-12 01:07 UTC, merged